# Generated by Django 2.2.7 on 2019-12-02 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_starts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inserire tempo di avvio')),
                ('timestamp_now', models.DateField(auto_now_add=True)),
                ('result_field', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('latandlong', models.CharField(default='Seppia', max_length=50)),
                ('my_search_query', models.CharField(max_length=250)),
                ('wanna_check_distance', models.BooleanField(default=True)),
                ('initialize', models.CharField(default='N', max_length=1)),
                ('job_timeout', models.CharField(default=900, max_length=9)),
                ('job timeout', models.CharField(default='00:15', max_length=25)),
            ],
            options={
                'ordering': ['-my_search_query'],
                'permissions': (('can_publish', 'Can Publish Posts'),),
            },
        ),
    ]
