# Generated by Django 2.2 on 2019-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0002_mysearch_result_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearch',
            name='geolocation',
            field=models.CharField(default='Seppia', max_length=250),
            preserve_default=False,
        ),
    ]
