# Generated by Django 2.2 on 2019-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0003_mysearch_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearch',
            name='initialize',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='mysearch',
            name='my_search_query',
            field=models.CharField(default='no query', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysearch',
            name='wanna_check_distance',
            field=models.BooleanField(default=True),
        ),
    ]
