# Generated by Django 2.2 on 2019-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0005_mysearch_latandlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearch',
            name='job_timeout',
            field=models.CharField(default=1800, max_length=6),
            preserve_default=False,
        ),
    ]
