# Generated by Django 2.2 on 2019-05-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0007_auto_20190512_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysearch',
            options={'ordering': ['-my_search_query'], 'permissions': (('can_publish', 'Can Publish Posts'),)},
        ),
    ]
