# Generated by Django 2.2 on 2019-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0010_auto_20190602_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='insert_job_timeout',
            field=models.CharField(default='00:15', max_length=5),
        ),
    ]
