# Generated by Django 2.2 on 2019-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0011_auto_20190602_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysearch',
            name='insert_job_timeout',
        ),
        migrations.AddField(
            model_name='mysearch',
            name='job timeout',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
