# Generated by Django 2.2 on 2019-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0012_auto_20190602_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='job timeout',
            field=models.CharField(default='00:15', max_length=5),
        ),
    ]
