# Generated by Django 2.2 on 2019-07-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0015_auto_20190602_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySearch',
        ),
    ]
