# Generated by Django 2.2 on 2019-08-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0017_mysearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearch',
            name='job time scheduler',
            field=models.CharField(default='now', max_length=5),
        ),
    ]
