# Generated by Django 2.2 on 2019-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0019_auto_20190803_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='job_starts',
            field=models.TimeField(default='now'),
        ),
    ]
