# Generated by Django 2.2 on 2019-11-06 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0020_auto_20191106_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='job_starts',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 1, 7, 0, 815606)),
        ),
    ]
