# Generated by Django 2.2 on 2019-11-06 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0024_auto_20191106_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='job_starts',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 15, 16, 70105, tzinfo=utc), verbose_name='Inserire tempo di avvio'),
        ),
    ]
