# Generated by Django 2.2 on 2019-11-06 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ADsPy_checker', '0025_auto_20191106_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysearch',
            name='job_starts',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inserire tempo di avvio'),
        ),
    ]
